apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: java-task
spec:
  workspaces:
  - name: common
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone https://github.com/7shivam/application-emp.git
    - name: mvn
      image: maven
      script: |
        mvn clean install -DskipTests
    - name: docker-image-build
      image: alpine
      script: |
        docker build -t emp-management-system-backend-java .