apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: / efs
    server: 172.31.23.64
  persistentVolumeReclaimPolicy: Retain 